name: Build dashboard.json from Excel

on:
  push:
    paths:
      - 'dashboard.xlsx'
      - 'excel-to-json.js'
      - '.github/workflows/excel-to-json.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i xlsx
      - run: node excel-to-json.js
      - name: Commit JSON if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/dashboard.json
          git diff --cached --quiet || git commit -m "Auto-build dashboard.json from Excel"
      - run: git push
